baseURL: https://jeremyboyle.dev

languageCode: en-us
title: "Jeremy Boyle"

languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: /images/bg.jpg
  # specify whether you want to write some blog posts or not
  enableBlogPost: false
  logo:
    favicon: images/favicon.png
  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
  # Provide newsletter configuration.
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form
    enable: false
    # specify which newsletter provider you want to use
    provider: mailchimp
    # specify the target URL for the subscription form
    mailchimpURL: https://github
